config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "home#index"

  get "site_rules", to: "static_pages#site_rules"
  get "errors/not_found", to: "errors#not_found"

  resources :users, only: %i[show index]

  resources :categories do
    resources :forums
  end

  resources :forums do
    resources :topics
  end

  resources :topics do
    resources :comments
  end
end

app/models/forum.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: forums
#
#  id          :bigint           not null, primary key
#  description :string
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           default(1), not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_forums_on_category_id  (category_id)
#  index_forums_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Forum < ApplicationRecord
  include ActionView::Helpers::DateHelper

  belongs_to :user
  belongs_to :category
  has_many :topics, dependent: :destroy

  validates :name, presence: true

  def total_comments
    Comment.joins(:topic).where(topics: { forum_id: id }).count
  end

  def total_topics
    Topic.where(forum_id: id).count
  end

  def last_comment
    Comment.joins(:topic).where(topics: { forum_id: id }).order(created_at: :desc).first
  end

  def last_comment_info
    return nil unless (last_comment = self.last_comment)

    "#{last_comment.user.username} #{time_ago_in_words(last_comment.created_at)} ago"
  end

  def last_comment_time
    last_comment&.created_at
  end
end

app/controllers/forums_controller.rb
# frozen_string_literal: true

class ForumsController < ApplicationController
  before_action :set_forum, only: %i[show update destroy]
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def index
    @categories = Category.all.includes(forums: { topics: :comments })
    @presenter = BreadcrumbPresenter.new(@forum, view_context)
    @breadcrumbs = @presenter.breadcrumbs
  end

  def show
    @pagy, @topics = pagy(@forum.topics.includes(:user, :comments), items: 10)
    @presenter = BreadcrumbPresenter.new(@forum, view_context)
    @breadcrumbs = @presenter.breadcrumbs
    @users_presenter = UsersPresenter.new(User.all)
  end

  def new
    @forum = Forum.new(user: current_user)
  end

  def create
    @forum = current_user.forums.build(forum_params)
    authorize @forum

    if @forum.save
      redirect_to forums_path, notice: t(".success")
    else
      render :new
    end
  end

  def update
    if @forum.update(forum_params)
      redirect_to forums_path, notice: t(".success")
    else
      render :edit
    end
  end

  def destroy
    authorize @forum
    @forum.destroy

    redirect_to forums_path, notice: t(".success")
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:name, :description, :category_id)
  end
end

app/views/forums/_form.html.erb
<%= form_with(model: forum, local: true) do |form| %>
  <%= render(ErrorMessagesComponent.new(resource: forum)) %>

  <div class="stack">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="stack">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%= form.collection_select :category_id, Category.all, :id, :name %>

  <div class="btn-group">
    <%= link_to t("go_back"), :back, class: "btn" %>
    <%= form.submit t("submit"), class: "btn" %>
  </div>
<% end %>

app/views/forums/_table_body.html.erb
<tbody class="category-table-body">
  <% category.forums.each do |forum| %>
    <%= render(ForumComponent.new(forum: forum)) %>
  <% end %>
</tbody>

app/views/forums/_table_header.html.erb
<thead>
  <tr class="category-table-row">
    <td colspan="6" class="nforumcaption">
      <span class="category-heading-text">
        <%= category.name %>
      </span>
      <div class="btn-group">
        <%= render(EditButtonComponent.new(record: category, policy: policy(category))) %>
        <%= render(DeleteButtonComponent.new(record: category, policy: policy(category))) %>
      </div>
    </td>
  </tr>

  <tr>
    <td colspan="2" style="text-align:center" class="nforumcaption2">Forums</td>
    <td style="text-align:center" class="nforumcaption2"><%= t("topics") %></td>
    <td style="text-align:center" class="nforumcaption2"><%= t("replies") %></td>
    <td style="text-align:center; width: fit-content; white-space: nowrap;" class="nforumcaption2"><%= t("last_comment") %></td>
    <% if current_user&.admin? %>
      <td style="text-align:center" class="nforumcaption2"><%= t("actions") %></td>
    <% end %>
  </tr>
</thead>

app/views/forums/edit.html.erb
<h1><%= t("edit_forum") %></h1>
<%= render "form", forum: @forum %>

app/views/forums/index.html.erb
<!-- Page title -->
<% content_for :title, "Forums" %>

<!-- Page content -->
<%= render(CardComponent.new(title: t("forums"))) do %>
  <% @categories.each do |category| %>
    <table class="nforumholder">
      <%= render("forums/table_header", category: category) %>
      <%= render("forums/table_body", category: category) %>
    </table>
  <% end %>
  <div class="btn-group">
    <% if current_user&.admin? %>
      <%= link_to t("new_category"),
      new_category_path,
      class: "btn",
      id: "new_category_link" %>
      <%= link_to t("new_forum"), new_forum_path, class: "btn" %>
    <% end %>
  </div>
<% end %>

app/views/forums/new.html.erb
<%= render(CardComponent.new(title: t("new_forum"), id: "new_forum")) do %>
  <h1><%= t("new_forum") %></h1>
  <%= render "form", forum: @forum %>
<% end %>

app/views/forums/show.html.erb
<!-- Page title -->
<% content_for :title, "#{@forum.name} / Forums" %>

<%= render(CardComponent.new(title: t("forums"))) do %>
  <%= render(BreadcrumbsComponent.new(items: @breadcrumbs)) %>
  <table style="width:100%">
    <tbody>
      <tr>
        <td style="width:80%">
          <div class="title-logo">
            <%= image_tag("e.png") %>
            <b>
              <%= @forum.name %>
            </b>
          </div>
          <%= t("go_to_page") %>&nbsp; [<span class="nextprev_current" style="text-decoration:underline">1</span>]
          <a class="nextprev_link">2</a>
          <a class="nextprev_link">3</a>
          ...
          <a class="nextprev_link">89</a>
          <a class="nextprev_link">90</a>
          <a class="nextprev_link">91</a>

          <%= render(PaginationComponent.new(pagy: @pagy, records: @topics)) %>
        </td>
        <td style="width:20%; text-align:right; vertical-align:bottom;">
        </td>
        <td style="width:20%; text-align:right; vertical-align:bottom;">
          <% if policy(@forum).create_topic? %>
            <%= link_to new_forum_topic_path(@forum) do %>
              <%= image_tag("English_newthread.png") %>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>

  <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
    <tbody>
      <tr>
        <td style="width:3%" class="nforumcaption2">&nbsp;</td>
        <td style="width:47%" class="nforumcaption2"><%= t("topic") %></td>
        <td style="width:20%; text-align:center" class="nforumcaption2"><%= t("starter") %></td>
        <td style="width:5%; text-align:center" class="nforumcaption2"><%= t("replies") %></td>
        <td style="width:5%; text-align:center" class="nforumcaption2">Views</td>
        <td style="width:20%; text-align:center; width: fit-content; white-space: nowrap;" class="nforumcaption2"><%= t("last_comment") %></td>
      </tr>

      <% if @topics.where(sticky: true).or(@topics.where(announcement: true)).any? %>

        <tr>
          <td class="forumheader">&nbsp;</td>
          <td colspan="6" class="forumheader">
            <span class="mediumtext">
              <b><%= t("important_threads") %></b>
            </span>
          </td>
        </tr>

        <%# Important (Sticky) Threads %>
        <% @topics.where(sticky: true).or(@topics.where(announcement: true))
          .order(announcement: :desc, created_at: :desc).each do |topic| %>
          <tr>
            <td
              style="vertical-align:middle; text-align:center; width:3%"
              class="nforumview1"
            >
              <% if topic.announcement? %>
                <%= image_tag("announce.png") %>
              <% else %>
                <%= image_tag("sticky_1.png") %>
              <% end %>
            </td>

            <td
              style="vertical-align:middle; text-align:left; width:47%"
              class="nforumview1"
            >
              <table style="width:100%">
                <tbody>
                  <tr>
                    <td style="width:90%">
                      <span class="mediumtext">
                        <b>
                          <%= link_to topic.title, [@forum, topic] %>
                        </b>
                      </span>
                      <span class="smalltext"></span>
                    </td>
                    <td style="width:10%; white-space:nowrap;"></td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td
              style="vertical-align:top; text-align:center; width:20%"
              class="nforumview2"
            >
              <span class="smalltext">
                <b>
                  <%= link_to topic.user.username, user_url(topic.user) %>
                </b>
                <br/>
                <%= topic.created_at.strftime("%a %b %d %Y, %I:%M%p") %>
              </span>
            </td>

            <td
              style="vertical-align:center; text-align:center; width:5%"
              class="nforumview2"
            >
              <span class="smalltext">
                <%= topic.comments_count %>
              </span>
            </td>

            <td
              style="vertical-align:center; text-align:center; width:5%"
              class="nforumview2"
            >
              <span class="smalltext">0</span>
            </td>

            <td
              style="vertical-align:top; text-align:center; width:20%"
              class="nforumview2"
            >
              <span class="smalltext">
                <%= link_to topic.user.username, user_url(topic.user) %>
                <br/>
                <%= topic.created_at.strftime("%a %b %d %Y, %I:%M%p") %>
              </span>
            </td>
          </tr>
        <% end %>
      <% end %>

      <tr>
        <td class="forumheader">&nbsp;</td>
        <td colspan="6" class="forumheader">
          <span class="mediumtext">
            <b><%= t("forum_threads") %></b>
          </span>
        </td>
      </tr>

      <% if @topics.where(sticky: false).or(@topics.where(announcement: false)).any? %>
        <% @topics.where(sticky: false).and(@topics.where(announcement: false)).each do |topic| %>
          <tr>
            <td
              style="vertical-align:middle; text-align:center; width:3%"
              class="nforumview1"
            >
              <%= image_tag("nonew_popular.png") %>
            </td>

            <td
              style="vertical-align:middle; text-align:left; width:47%"
              class="nforumview1"
            >
              <table style="width:100%">
                <tbody>
                  <tr>
                    <td style="width:90%">
                      <span class="mediumtext">
                        <b>
                          <%= link_to topic.title, [@forum, topic] %>
                        </b>
                      </span>
                      <span class="smalltext"></span>
                    </td>
                    <td style="width:10%; white-space:nowrap;"></td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td
              style="vertical-align:top; text-align:center; width:20%"
              class="nforumview2"
            >
              <span class="smalltext">
                <b>
                  <%= link_to topic.user.username, user_url(topic.user) %>
                </b>
                <br/>
                <%= topic.created_at.strftime("%a %b %d %Y, %I:%M%p") %>
              </span>
            </td>

            <td
              style="vertical-align:center; text-align:center; width:5%"
              class="nforumview2"
            >
              <span class="smalltext">
                <%= topic.comments_count %>
              </span>
            </td>

            <td
              style="vertical-align:center; text-align:center; width:5%"
              class="nforumview2"
            >
              <span class="smalltext">0</span>
            </td>

            <td
              style="vertical-align:top; text-align:center; width:20%"
              class="nforumview2"
            >
              <span class="smalltext">
                <%= link_to topic.user.username, user_url(topic.user) %>
                <br/>
                <%= topic.created_at.strftime("%a %b %d %Y, %I:%M%p") %>
              </span>
            </td>
          </tr>
        <% end %>
      <% else %>
        <p><%= t("there_are_no_topics_in_this_forum_yet") %></p>
      <% end %>
    </tbody>
  </table>

  <table style="width:100%">
    <tbody>
      <tr>
        <td style="width:80%">
          <span class="mediumtext"><%= t("go_to_page") %>&nbsp; [<span class="nextprev_current" style="text-decoration:underline">1</span>]
            <a class="nextprev_link">2</a>
            <a class="nextprev_link">3</a>
            ...
            <a class="nextprev_link">89</a>
            <a class="nextprev_link">90</a>
            <a class="nextprev_link">91</a>
          </span>
          <form>
            <p><%= t("jump_to_forum") %>:
              <select name="forumjump" class="tbox">
                <option value="2">General Chatting</option>
                <option value="8">Sale and Trade</option>
                <option value="9">General Science and Electronics</option>
                <option value="10">Electromagnetic Radiation</option>
                <option value="11">Electromagnetic Projectile Accelerators</option>
                <option value="12">High Voltage</option>
                <option value="13">Tesla Coils</option>
                <option value="14">Chemistry</option>
                <option value="15">Computer Science</option>
                <option value="16">Projects</option>
                <option value="20">Archive Discussion</option>
                <option value="19">Suggestion Box</option>
                <option value="21">Attachments</option>
                <option value="23">HvWiki Discussion</option>
              </select>

              <input class="button" type="submit" name="fjsubmit" value="Go"/>&nbsp;&nbsp;&nbsp;&nbsp;
              <td style="width:20%; text-align:right"/>
            </p>
          </form>

        </td>
      </tr>
    </tbody>
  </table>

  <div class="spacer">
    <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
      <tbody>
        <tr>
          <td style="vertical-align:center; width:50%" class="nforumview3">
            <span class="smalltext">This forum is moderated by:
              <%= @users_presenter.moderators_list %>
            </span>
          </td>

          <td
            style="text-align:right; vertical-align:center; width:50%"
            class="nforumview3"
          >
            <span class="smalltext">1 user is browsing this forum at the moment (0 members, 1 guest)
            </span>
          </td>
        </tr>

        <tr>
          <td style="vertical-align:center; width:50%" class="nforumview4">
            <table style="width:100%">
              <tbody>
                <tr>
                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("new_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">New comments</td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("nonew_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">
                    <%= t("no_new_comments") %>
                  </td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("sticky_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">Sticky</td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("announce_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">
                    <%= t("announcement") %>
                  </td>
                </tr>

                <tr>
                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("new_popular_small.png") %>
                  </td>

                  <td style="width:2%" class="smallblacktext">
                    <%= t("new_comments_popular") %>
                  </td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("nonew_popular_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">
                    <%= t("no_new_comments_popular") %>
                  </td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("sticky_closed_small.png") %>
                  </td>

                  <td style="width:10%" class="smallblacktext">
                    <%= t("sticky_closed") %>
                  </td>

                  <td style="vertical-align:middle; text-align:center; width:2%">
                    <%= image_tag("closed_small.png") %>>
                  </td>

                  <td style="width:10%" class="smallblacktext">
                    <%= t("closed_thread") %>
                  </td>
                </tr>
              </tbody>
            </table>
          </td>

          <td
            style="vertical-align:center; text-align:center; width:50%"
            class="nforumview4"
          >
            <%= t("you") %>
            <b><%= t("can") %></b>
            <%= t("start_new_threads_you") %>
            <b><%= t("can") %></b>
            <%= t("comment_replies_you") %>
            <b><%= t("can") %></b>
            <%= t("edit_your_comments") %>
            <br/>
            <br/>
            <form method="get" action="../../search.php">
              <p>
                <input class="tbox" type="text" name="q" size="20" value="" maxlength="50"/>
                <input type="hidden" name="r" value="0 "/>
                <input type="hidden" name="ref" value="forum "/>
                <input class="button" type="submit" name="s" value="Search "/>
              </p>
            </form>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="nforumdisclaimer" style="text-align:center"><%= t("powered_by") %>
    <b><%= t("coffee") %></b>
  </div>

<% end %>