config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "home#index"

  get "site_rules", to: "static_pages#site_rules"
  get "errors/not_found", to: "errors#not_found"

  resources :users, only: %i[show index]

  resources :categories do
    resources :forums
  end

  resources :forums do
    resources :topics
  end

  resources :topics do
    resources :comments
  end
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id                :bigint           not null, primary key
#  content           :text
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#  topic_id          :integer          not null
#  user_id           :integer
#
# Indexes
#
#  index_comments_on_topic_id  (topic_id)
#  index_comments_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (topic_id => topics.id)
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic, counter_cache: true
  belongs_to :parent_comment, class_name: "Comment", optional: true

  has_many :replies, class_name: "Comment", foreign_key: :parent_comment_id, dependent: :nullify, inverse_of: :parent_comment

  validates :content, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_topic, only: %i[show new create edit update destroy]
  before_action :set_comment, only: %i[show edit update destroy]

  def index
    @comments = Comment.all
  end

  def show; end

  def new
    @comment = Comment.new
    @parent_comment_id = params[:parent_comment_id]
  end

  def create
    @comment = build_comment
    set_parent_comment if params[:parent_comment_id]

    if @comment.save
      redirect_to forum_topic_path(@topic.forum, @topic), notice: t(".success")
    else
      render :new, status: :unprocessable_entity, flash: { error: t(".failure") }
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to forum_topic_path(@topic.forum, @topic), notice: t(".success")
    else
      render :edit, status: :unprocessable_entity, flash: { error: t(".failure") }
    end
  end

  def destroy
    authorize @comment

    if @comment.destroy
      redirect_to forum_topic_path(@topic.forum, @topic), notice: t(".success")
    else
      render :show, status: :unprocessable_entity, flash: { error: t(".failure") }
    end
  end

  private

  def set_topic
    @topic = Topic.find(params[:topic_id])
  end

  def build_comment
    @topic.comments.build(comment_params).tap do |comment|
      comment.user = current_user
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_parent_comment
    parent_comment = Comment.find(params[:parent_comment_id])
    @comment.parent_comment_id = parent_comment.id
  end

  def comment_params
    params.require(:comment).permit(:content, :parent_comment_id)
  end
end

app/views/comments/_comment.html.erb
<div class="spacer" id="comment-<%= comment.id %>">
  <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
    <tbody>
      <tr>
        <td class="nforumcaption3" style="vertical-align:middle; width:20%;">
          <b>
            <%= link_to comment.user.username, user_url(comment.user) %>
          </b>
        </td>
        <td class="nforumcaption3" style="vertical-align:middle; width:80%;">
          <table cellspacing="0" cellpadding="0" style="width:100%">
            <tbody>
              <tr>
                <td class="smallblacktext">
                  <a id="" href="">
                    <%= image_tag("post.png") %>
                  </a>
                  <%= comment.created_at.strftime("%d %b %Y at %I:%M %p") %>
                </td>
                <td style="text-align:right">
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
      <tr>
        <%= render(UserCardComponent.new(user: comment.user)) %>
        <td class="nforumthread" style="vertical-align:top">
          <% if comment.parent_comment %>
            <div class="indent">
              <em>
                <%= comment.parent_comment.user.username %>
                <%= t("wrote") %>
              </em>
              ...
              <br>
              <br>
              <%= comment.parent_comment.content %>
              <br>
            </div>
          <% end %>
          <br>
          <%= comment.content %>
          <br>
          <% if comment.user&.signature %>
            <hr style="width:15%; text-align:left">
            <span class="smalltext">
              <%= comment.user.signature %>
            </span>
          <% end %>
        </td>
      </tr>
      <tr>
        <td class="nforumthread2"><span class="smallblacktext"><%= link_to t("back_to_top"),
            nil,
            id: "back-to-top",
            onclick: "window.scrollTo({top: 0, behavior: 'smooth'});" %>
          </span>
        </td>
        <td class="nforumthread2" style="vertical-align:top">
          <table cellspacing="0" cellpadding="0" style="width:100%">
            <tbody>
              <tr>
                <td style="text-align:right">

                  <div class="btn-group">
                    <% if policy(comment).create? %>
                      <%= link_to new_topic_comment_path(@topic, parent_comment_id: comment.id),
                                  class: "btn",
                                  data: { turbo_frame: "new_comment_#{comment.id}" } do %>
                        <%= t("comments.actions.reply") %>
                      <% end %>
                    <% end %>

                    <% if policy(comment).edit? %>
                      <%= link_to edit_topic_comment_path(@topic, comment),
                                  class: "btn",
                                  data: { turbo_frame: "comment_#{comment.id}" } do %>
                        <%= t("comments.actions.edit") %>
                      <% end %>
                    <% end %>

                    <% if policy(comment).destroy? %>
                      <%= button_to [@topic, comment],
                                    class: "btn",
                                    method: :delete,
                                    form: { data: { turbo_confirm: t("comments.confirmation.delete") } } do %>
                        <%= t("comments.actions.delete") %>
                      <% end %>
                    <% end %>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@topic, comment], local: true) do |form| %>
  <%= render(ErrorMessagesComponent.new(resource: comment)) %>

  <%= form.hidden_field :parent_comment_id, value: @parent_comment_id %>

  <div class="stack">
    <%= form.label t("reply") %>
    <%= form.text_area :content %>
  </div>

  <div class="btn-group">
    <%= form.submit t("submit"), class: "btn" %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append "comments" do %>
  <%= render @comment %>
<% end %>

app/views/comments/edit.html.erb
<div class="custom-card p-8">
  <h1><%= t("edit_comment") %></h1>

  <%= render "form", comment: @comment %>
</div>

app/views/comments/new.html.erb
<%= render(CardComponent.new(title: t("new_comment"), id: "new_comment")) do %>
  <h1><%= t("new_comment") %></h1>
  <%= render "form", comment: @comment %>
<% end %>