config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "home#index"

  get "site_rules", to: "static_pages#site_rules"
  get "errors/not_found", to: "errors#not_found"

  resources :users, only: %i[show index]

  resources :categories do
    resources :forums
  end

  resources :forums do
    resources :topics
  end

  resources :topics do
    resources :comments
  end
end

app/models/topic.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: topics
#
#  id             :bigint           not null, primary key
#  announcement   :boolean
#  comments_count :integer          default(0), not null
#  content        :text
#  sticky         :boolean
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  forum_id       :integer          not null
#  user_id        :integer
#
# Indexes
#
#  index_topics_on_forum_id  (forum_id)
#  index_topics_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (forum_id => forums.id)
#
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :forum
  has_many :comments, dependent: :destroy

  validates :title, presence: true

  def sticky?
    sticky
  end

  def mark_as_sticky!
    update(sticky: true) unless sticky?
  end

  def unmark_as_sticky!
    update(sticky: false) if sticky?
  end

  def announcement?
    announcement
  end

  def mark_as_announcement!
    update(announcement: true) unless announcement?
  end

  def unmark_as_announcement!
    update(announcement: false) if announcement?
  end
end

app/controllers/topics_controller.rb
# frozen_string_literal: true

class TopicsController < ApplicationController
  before_action :set_forum
  before_action :set_topic, only: %i[show edit update destroy]

  rate_limit to: 10, within: 5.minutes, only: [ :create ],
  with: -> { redirect_to root_path, alert: "You're posting too quickly. Please wait a few minutes." }

  def index
    @topics = Topic.page(params[:page]).per(10).includes(:user, :comments)
  end

  def show
    @topic = Topic.find(params[:id])
    @comments = @topic.comments.page(params[:page]).per(10)

    @breadcrumbs = [
      { title: "4hv.org", path: root_path },
      { title: "Forums", path: forums_path },
      { title: @forum.name, path: forum_path(@forum) },
      { title: @topic.title, path: forum_topic_path(@forum, @topic) }
    ]
    @users_presenter = UsersPresenter.new(User.all)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = @forum.topics.build(topic_params)
    @topic.user = current_user
    authorize @topic

    if @topic.save
      redirect_to forum_topic_path(@forum, @topic), flash: { success: t(".success") }
    else
      render :new, status: :unprocessable_entity, flash: { error: t(".failure") }
    end
  end

  def edit
    @topic = @forum.topics.find(params[:id])
  end

  def update
    @topic = @forum.topics.find(params[:id])

    if @topic.update(topic_params)
      redirect_to forum_topic_path(@forum, @topic), notice: t(".success")
    else
      render :edit
    end
  end

  def destroy
    authorize @topic
    @topic.destroy

    redirect_to forum_path(@forum), notice: t(".success")
  end

  def toggle_sticky
    @topic = Topic.find(params[:id])
    authorize @topic, :toggle_sticky?

    if @topic.sticky?
      @topic.unmark_as_sticky!
    else
      @topic.mark_as_sticky!
    end

    redirect_to [ @forum, @topic ], notice: t("topic_stickiness_updated")
  end

  def toggle_announcement
    @topic = Topic.find(params[:id])
    authorize @topic, :toggle_announcement?

    if @topic.announcement?
      @topic.unmark_as_announcement!
    else
      @topic.mark_as_announcement!
    end

    redirect_to [ @forum, @topic ], notice: t("topic_stickiness_updated")
  end

  private

  def set_forum
    @forum = Forum.find(params[:forum_id])
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:title, :content, :sticky, :announcement, :forum_id, :user_id)
  end
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: [@forum, topic], local: true) do |form| %>
  <%= render(ErrorMessagesComponent.new(resource: topic)) %>

  <div class="stack">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="stack">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="stack">
    <%= form.label :sticky %>
    <%= form.check_box :sticky %>

    <%= form.label :announcement %>
    <%= form.check_box :announcement %>
  </div>

  <div class="btn-group">
    <%= link_to t("go_back"), :back, class: "btn" %>
    <%= form.submit t("create_topic"), class: "btn" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<table style="width:100%">
  <tbody>
    <tr>
      <td style="width:60%">
        <div class="title-logo">
          <%= image_tag("e.png") %>
          <b>
            <%= @topic.title %>
          </b>
        </div>
        <br>
        <%= t("go_to_page") %>&nbsp;
        <div class="pagination" style="display: inline-block;">
          <%= paginate @comments %>
        </div>
      </td>
      <td style="width:40%; text-align: right; vertical-align:bottom;"></td>
    </tr>
  </tbody>
</table>

app/views/topics/edit.html.erb
<div class="custom-card p-8">
  <h1><%= t("edit_topic") %></h1>

  <%= render "form", forum: @forum, topic: @topic %>
</div>

app/views/topics/new.html.erb
<%= render(CardComponent.new(title: t("new_topic"), id: "new_topic")) do %>
  <h1><%= t("new_topic") %></h1>
  <%= render "form", topic: @topic %>
<% end %>

app/views/topics/show.html.erb
<!-- Page title -->
<% content_for :title, "#{@topic.title} / #{@topic.forum.name} / Forums" %>

<%= render(CardComponent.new(title: t("forums"))) do %>
  <td class="bodymain">
    <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
      <tbody>
        <%= render(BreadcrumbsComponent.new(items: @breadcrumbs)) %>
        <tr>
          <td class="nforumcaption2" colspan="2">
            <table cellspacing="0" cellpadding="0" style="width:100%">
              <tbody>
                <tr>
                  <td>&lt;&lt;
                    <a href=""><%= t("previous_thread") %></a>
                    |
                    <a href=""><%= t("next_thread") %></a>
                    &gt;&gt;
                  </td>
                  <td style="text-align:right">&nbsp;&nbsp;</td>
                </tr>
              </tbody>
            </table>
          </td>
        </tr>
      </tbody>
    </table>
    <br>
    <% if params[:page].to_i <= 1 %>
      <%= render partial: "topics/topic", locals: { topic: @topic } %>
    <% end %>
    <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
      <tbody>
        <tr>
          <td style="width:20%; text-align:center" class="nforumcaption2">
            <%= t("author") %>
          </td>
          <td style="width:80%; text-align:center" class="nforumcaption2">
            <!--
            <%= t("comment") %>
            -->
          </td>
        </tr>
      </tbody>
    </table>

    <div class="spacer">
      <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
        <tbody>
          <% if params[:page].to_i <= 1 %>
            <tr>
              <td class="nforumcaption3" style="vertical-align:middle; width:20%;">
                <a href="../../user.php?id.1225"><b>
                    <%= link_to @topic.user.username, user_url(@topic.user) %>
                  </b></a>
              </td>
              <td class="nforumcaption3" style="vertical-align:middle; width:80%;">
                <table cellspacing="0" cellpadding="0" style="width:100%">
                  <tbody>
                    <tr>
                      <td class="smallblacktext">
                        <a id="comment_66240" href="">
                          <%= image_tag("post.png") %>
                        </a>
                        <%= @topic.created_at.strftime("%d %b %Y at %I:%M %p") %>
                      </td>
                      <td style="text-align:right">
                        <a href="/print.php?plugin:forum.66240">
                          <%= image_tag("printer.png") %>
                        </a>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
            <tr>
              <%= render(UserCardComponent.new(user: @topic.user)) %>
              <td class="nforumthread" style="vertical-align:top">
                <%= @topic.content %><br><br><br><br><br><br>
                <% if @topic.user&.signature %>
                  <hr style="width:15%; text-align:left">
                  <span class="smalltext">
                    <%= @topic.user.signature %>
                  </span>
                <% end %>
              </td>
            </tr>
            <tr>
              <td class="nforumthread2"><span class="smallblacktext"><%= link_to t("back_to_top"),
                  nil,
                  id: "back-to-top",
                  onclick: "window.scrollTo({top: 0, behavior: 'smooth'});" %>
                </span></td>
              <td class="nforumthread2" style="vertical-align:top">
                <table cellspacing="0" cellpadding="0" style="width:100%">
                  <tbody>
                    <tr>
                      <td style="text-align:right">
                        <div class="btn-group">
                          <% if policy(@topic).edit? %>
                            <%= link_to t("edit_topic"), edit_forum_topic_path(@forum, @topic), class: "btn" %>
                          <% end %>
                          <% if policy(@topic).destroy? %>
                            <%= button_to t("delete"),
                            [@forum, @topic],
                            class: "btn",
                            method: :delete,
                            data: {
                              confirm: t("are_you_sure"),
                              turbo_confirm: t("are_you_sure"),
                            } %>
                          <% end %>
                        </div>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% if @topic.comments.any? %>
      <div class="comments">
        <% @comments.each do |comment| %>
          <%= render comment %>
        <% end %>
      </div>
    <% else %>
      <p><%= t("there_are_no_comments_in_this_topic_yet") %></p>
    <% end %>
    <% if policy(@topic).create_comment? %>
      <%= render "comments/form", comment: @topic.comments.build %>
    <% end %>
    <div class="spacer">
      <div class="forumheader">
        <%= t("go_to_page") %>&nbsp;
        <div class="pagination" style="display: inline-block;">
          <%= paginate @comments %>
        </div>
      </div>
      <br>
      <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td style="width:50%; text-align:left; vertical-align:top" class="nforumthread">
              <b><%= t("moderators") %>:
                <%= @users_presenter.moderators_list %></b><br>
              <form method="comment" action="">
                <p><%= t("jump") %>:
                  <select name="forumjump" class="tbox">
                    <option value="2">General Chatting</option>
                    <option value="8">Sale and Trade</option>
                    <option value="9">General Science and Electronics</option>
                    <option value="10">Electromagnetic Radiation</option>
                    <option value="11">Electromagnetic Projectile Accelerators</option>
                    <option value="12">High Voltage</option>
                    <option value="13">Tesla Coils</option>
                    <option value="14">Chemistry</option>
                    <option value="15">Computer Science</option>
                    <option value="16">Projects</option>
                    <option value="20">Archive Discussion</option>
                    <option value="19">Suggestion Box</option>
                    <option value="21">Attachments</option>
                    <option value="23">HvWiki Discussion</option>
                  </select>
                  <input class="button" type="submit" name="fjsubmit" value="Go">&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to t("back_to_top"),
                  nil,
                  id: "back-to-top",
                  onclick: "window.scrollTo({top: 0, behavior: 'smooth'});" %>
                </p>
              </form>
            </td>
            <td
              style="width:50%; text-align:right; vertical-align:top"
              class="nforumthread"
            >
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="spacer">
      <table style="width:100%" class="nforumholder" cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td style="text-align:center" class="nforumthread2">
            </td>
          </tr>
        </tbody>
      </table>
      <div class="nforumdisclaimer" style="text-align:center"><%= t("powered_by") %>
        <b><%= t("coffee") %></b>
      </div>
    </div>
  </td>
<% end %>