config/routes.rb
# frozen_string_literal: true

# == Route Map
#

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  root "home#index"

  get "site_rules", to: "static_pages#site_rules"
  get "errors/not_found", to: "errors#not_found"

  resources :users, only: %i[show index]

  resources :categories do
    resources :forums
  end

  resources :forums do
    resources :topics
  end

  resources :topics do
    resources :comments
  end
end

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <p class="flash flash-notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p class="flash flash-alert""><%= flash[:alert] %></p>
<% end %>
<% if flash[:error] %>
  <p class="flash flash-error"><%= flash[:error] %></p>
<% end %>
<% if flash[:success] %>
  <p class="flash flash-success"><%= flash[:success] %></p>
<% end %>

app/views/shared/_sidebar.html.erb
<aside class="sidebar">
  <%= render(CardComponent.new(title: t("main_menu"))) do %>
    <ul>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= link_to t("home"), root_path, id: "home_link" %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= link_to t("forum"), forums_path, id: "forums_link" %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= link_to t("members"), users_path, id: "members_link" %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= t("member_map") %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= t("hv_wiki") %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= t("chat_room") %>
      </li>
      <li>
        <%= image_tag("bullet2.gif") %>
        <%= link_to t("site_rules"), site_rules_path, id: "site_rules_link" %>
      </li>
    </ul>
  <% end %>

  <%= render(CardComponent.new(title: t("welcome"))) do %>
    <div style="text-align: center">
      <% if user_signed_in? %>
        <div style="margin-bottom: 4px;">
          <%= t("welcome") %>
          <%= link_to current_user.username, current_user %>!
        </div>
        <div>
          <% if current_user&.admin? %>
            <div class="smalltext"><%= t("admin") %></div>
            <%= image_tag("English_main_admin.png") %>
          <% elsif current_user&.moderator? %>
            <div class="smalltext"><%= t("moderator") %></div>
            <%= image_tag("English_moderator.png") %>
          <% else %>
            <div class="smalltext"><%= t("user") %></div>
          <% end %>
          <div class="smalltext">
            <%= t("registered_member", number: current_user.id) %>
          </div>
          <%= button_to t("devise.sign_out"),
          destroy_user_session_path,
          method: :delete,
          class: "link-button" %>
        </div>
      <% else %>
        <%= render "devise/sessions/new" %>
        <div>
          [
          <%= link_to "Sign up", new_user_registration_path %>
          ]
        </div>
        <div>
          [
          <%= link_to "Forgot password?", new_user_password_path %>
          ]
        </div>
      <% end %>
    </div>
  <% end %>

  <%= render(CardComponent.new(title: t("online"))) do %>
    <ol class="online-stats">
      <li>
        <%= t("guests") %>:
        <%= @online_guests_count %>
      </li>
      <li>
        <%= t("members") %>:
        <%= @online_members_count %>
      </li>
      <li>
        <%= t("newest_member") %>:
        <%= @newest_member&.username %>
      </li>
      <li>
        <%= t("most_ever_online") %>:
        <%= @most_ever_online %>
      </li>
    </ol>
  <% end %>

  <%= render(CardComponent.new(title: "#{t("members_birthdays")}:")) do %>
    <td class="bodymain">
      <% if User.todays_birthdays.any? %>
        One birthday today, congrats!<br>
        <% User.todays_birthdays.each do |user| %>
          <%= link_to "#{user.username} (#{age(user)})", user_path(user) %><br>
        <% end %>
      <% end %>
      <%= t("next_birthdays") %>
      <% User.upcoming_birthdays.each do |user| %>
        <%= user.date_of_birth.to_char("MM/DD") %>
        <%= link_to "#{user.username} (#{age(user)})", user_path(user) %><br>
      <% end %>
    </td>
  <% end %>

  <%= render(CardComponent.new(title: t("contact"))) do %>
    <%= t("contact_sidebar_text") %>
  <% end %>

  <%= render(CardComponent.new(title: t("support_4hv"))) do %>
    <%= t("donate") %>
    <br/>
    <%= image_tag("paypal.gif") %>
  <% end %>
</aside>

app/views/shared/_site_content.html.erb
<div class="main-content">
  <div style="display: flex; flex-direction: column; gap: 1rem;">
    <%= yield %>
  </div>
</div>

app/views/shared/_site_footer.html.erb
<footer class="site-footer">
  <div class="container">
  </div>
</footer>

app/views/shared/_site_header.html.erb
<header>
  <div class="banner-container">
    <%= image_tag("logo.png", width: 200) %>
  </div>
  <hr/>
  <div class="nav-bar">
    <button class="menu-button">☰</button>
    <section class="search-bar">
      <input class="tbox search"/>
      <%= image_tag("search.png") %>
    </section>
  </div>
  <hr/>
</header>